# Generated by Django 2.2.13 on 2021-03-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ImageField(default=False, upload_to=None),
        ),
    ]
