# Generated by Django 2.2.13 on 2021-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210321_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('dpdescription', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
