# Generated by Django 2.2.13 on 2021-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210322_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dpabout',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
