# Generated by Django 2.2.13 on 2021-03-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
